"""Add DayPass and unified booking models

Revision ID: 00002
Revises: 00001
Create Date: 2026-09-09 18:28:24.569296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00002'
down_revision: Union[str, Sequence[str], None] = '00001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_passes',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('daily_capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    booking_type_enum = sa.Enum('SEAT', 'DAY_PASS', 'MEETING_ROOM', 'CONFERENCE_ROOM', name='bookingtype')
    booking_type_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('bookings', sa.Column('booking_type', booking_type_enum, nullable=False, server_default='SEAT'))
    op.add_column('bookings', sa.Column('location_id', sa.UUID(), nullable=True))
    op.add_column('bookings', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.add_column('bookings', sa.Column('day_pass_id', sa.UUID(), nullable=True))
    op.add_column('bookings', sa.Column('room_id', sa.UUID(), nullable=True))
    op.add_column('bookings', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('bookings', sa.Column('end_time', sa.Time(), nullable=True))
    op.alter_column('bookings', 'seat_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('bookings', 'time_slot_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'bookings', 'day_passes', ['day_pass_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'branches', ['branch_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'locations', ['location_id'], ['id'])
    op.add_column('rooms', sa.Column('room_type', sa.String(), nullable=False, server_default='WORKSPACE'))
    op.add_column('rooms', sa.Column('price_per_hour', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'price_per_hour')
    op.drop_column('rooms', 'room_type')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.alter_column('bookings', 'time_slot_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('bookings', 'seat_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('bookings', 'end_time')
    op.drop_column('bookings', 'start_time')
    op.drop_column('bookings', 'room_id')
    op.drop_column('bookings', 'day_pass_id')
    op.drop_column('bookings', 'branch_id')
    op.drop_column('bookings', 'location_id')
    op.drop_column('bookings', 'booking_type')
    op.drop_table('day_passes')
    # ### end Alembic commands ###
